
#Alacritty:

env:
  TERM: alacritty

window:
  padding:
    x: 9
    y: 4

    dynamic_padding:  true
    decoration: none

font:
  normal:
    family: Fira Code

  bold:
    family: Fira Code

  italic:
    family: Fira Code

  bold_italic:
    family: Fira Code

  size: 11.3

colors:
  primary:
    background: '#000000'
    foreground: '#ffffff'

  cursor:
    text:       '#eaeaea'
    background: '#404040'

  normal:
    black:    '#000000'
    red:      '#d54e53'
    green:    '#b9ca4a'
    yellow:   '#e6c547'
    blue:     '#7aa6da'
    magenta:  '#c397d8'
    cyan:     '#70c0ba'
    white:    '#eaeaea'

  bright:
    black:    '#666666'
    red:      '#ff3334'
    green:    '#9ec400'
    yellow:   '#e7c547'
    blue:     '#7aa6da'
    magenta:  '#b77ee0'
    cyan:     '#54ced6'
    white:    '#ffffff'

  dim:
    black:    '#000000'
    red:      '#8c3336'
    green:    '#7a8530'
    yellow:   '#97822e'
    blue:     '#506d8f'
    magenta:  '#80638e'
    cyan:     '#497e7a'
    white:    '#9a9a9a'

background_opacity: 0.90

cursor:
  style: Underline

  unfocused_hollow: false

live_config_reload: true


key_bindings:

  - { key: Key0, mods: Control, action: ResetFontSize }

  - { key: Equals, mods: Control, action: IncreaseFontSize }

  - { key: Add, mods: Control, action: IncreaseFontSize }

  - { key: Subtract, mods: Control, action: DecreaseFontSize }
   
  - { key: Minus, mods: Control, action: DecreaseFontSize }
